workflows:
  ios-workflow:
    name: Chechi Puttu iOS
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    working_directory: chechi_puttu_app
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build IPA
        script: flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/Runner.xcarchive
