// File generated by FlutterFire CLI — replace placeholders from Firebase Console:
// Project settings → Your apps → copy values into each [REPLACE] below, or run:
//   dart pub global activate flutterfire_cli
//   dart pub global run flutterfire_cli:flutterfire configure
//
// https://firebase.google.com/docs/flutter/setup

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjWBkl5uWzv32ktRGe4cRjGOPCqq-yY2k',
    appId: '1:316102307451:web:fd05bda542f43bb9633cde',
    messagingSenderId: '316102307451',
    projectId: 'chechi-puttu-kadai',
    authDomain: 'chechi-puttu-kadai.firebaseapp.com',
    storageBucket: 'chechi-puttu-kadai.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4UMn-rHxI0fYADsDBaVFEwle530ItXeE',
    appId: '1:316102307451:android:e6e31a57592f375a633cde',
    messagingSenderId: '316102307451',
    projectId: 'chechi-puttu-kadai',
    storageBucket: 'chechi-puttu-kadai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBSy9t2uxCMnK93vnjBmzJJjx5CNGg_Dc',
    appId: '1:316102307451:ios:7e850767a884148e633cde',
    messagingSenderId: '316102307451',
    projectId: 'chechi-puttu-kadai',
    storageBucket: 'chechi-puttu-kadai.firebasestorage.app',
    androidClientId: '316102307451-9o5ua4v3tftndnmuocaa3oa1l2fvggj7.apps.googleusercontent.com',
    iosClientId: '316102307451-l09t7egsunl83jmp6nk59blj2atp3oqc.apps.googleusercontent.com',
    iosBundleId: 'com.example.chechiPuttuApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBSy9t2uxCMnK93vnjBmzJJjx5CNGg_Dc',
    appId: '1:316102307451:ios:7e850767a884148e633cde',
    messagingSenderId: '316102307451',
    projectId: 'chechi-puttu-kadai',
    storageBucket: 'chechi-puttu-kadai.firebasestorage.app',
    androidClientId: '316102307451-9o5ua4v3tftndnmuocaa3oa1l2fvggj7.apps.googleusercontent.com',
    iosClientId: '316102307451-l09t7egsunl83jmp6nk59blj2atp3oqc.apps.googleusercontent.com',
    iosBundleId: 'com.example.chechiPuttuApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjWBkl5uWzv32ktRGe4cRjGOPCqq-yY2k',
    appId: '1:316102307451:web:858172d2fe851a5b633cde',
    messagingSenderId: '316102307451',
    projectId: 'chechi-puttu-kadai',
    authDomain: 'chechi-puttu-kadai.firebaseapp.com',
    storageBucket: 'chechi-puttu-kadai.firebasestorage.app',
  );

}